/* eslint-disable @typescript-eslint/no-explicit-any */
declare type AnyArray = Array<any>;

declare type AnyObject = Record<string, any>;

declare namespace NodeJS {
  interface ProcessEnv {
    key: string;
    id: string;
    static_path?: string;
  }
}

declare interface IComment {
  id: string;
  author: string;
  text: string;
  publishedAt: string;
  likeCount: number;
}

declare interface ICaption {
  id: string;
  language: string;
  name: string;
  trackKind: string;
  isAutoGenerated: boolean;
}

declare interface YouTubeCommentResponse {
  kind: string;
  etag: string;
  nextPageToken?: string;
  pageInfo: {
    totalResults: number;
    resultsPerPage: number;
  };
  items: Array<{
    kind: string;
    etag: string;
    id: string;
    snippet: {
      channelId: string;
      videoId: string;
      topLevelComment: {
        kind: string;
        etag: string;
        id: string;
        snippet: {
          channelId: string;
          videoId: string;
          textDisplay: string;
          textOriginal: string;
          authorDisplayName: string;
          authorProfileImageUrl: string;
          authorChannelUrl: string;
          authorChannelId: { value: string };
          canRate: boolean;
          viewerRating: string;
          likeCount: number;
          publishedAt: string;
          updatedAt: string;
        };
      };
      canReply: boolean;
      totalReplyCount: number;
      isPublic: boolean;
    };
    replies?: {
      comments: AnyArray;
    };
  }>;
}

declare interface IVideoInfo {
  id: string;
  title: string;
  description: string;
  channelId: string;
  channelTitle: string;
  publishedAt: string;
  duration: string;
  viewCount: string;
  likeCount: string;
  commentCount: string;
  categoryId: string;
  tags: string[];
  thumbnails: {
    default: IThumbnail;
    medium: IThumbnail;
    high: IThumbnail;
    standard?: IThumbnail;
    maxres?: IThumbnail;
  };
}

declare interface IThumbnail {
  url: string;
  width: number;
  height: number;
}

declare interface YouTubeVideoResponse {
  kind: string;
  etag: string;
  items: Array<{
    kind: string;
    etag: string;
    id: string;
    snippet: {
      publishedAt: string;
      channelId: string;
      title: string;
      description: string;
      thumbnails: {
        default: IThumbnail;
        medium: IThumbnail;
        high: IThumbnail;
        standard?: IThumbnail;
        maxres?: IThumbnail;
      };
      channelTitle: string;
      tags?: string[];
      categoryId: string;
      liveBroadcastContent: string;
      localized: {
        title: string;
        description: string;
      };
    };
    contentDetails: {
      duration: string;
      dimension: string;
      definition: string;
      caption: string;
      licensedContent: boolean;
      contentRating: AnyObject;
      projection: string;
    };
    statistics: {
      viewCount: string;
      likeCount: string;
      favoriteCount: string;
      commentCount: string;
    };
  }>;
  pageInfo: {
    totalResults: number;
    resultsPerPage: number;
  };
}

declare interface YouTubeCaptionsResponse {
  kind: string;
  etag: string;
  items: Array<{
    kind: string;
    etag: string;
    id: string;
    snippet: {
      videoId: string;
      lastUpdated: string;
      trackKind: string;
      language: string;
      name: string;
      audioTrackType?: string;
      isCC?: boolean;
      isLarge?: boolean;
      isEasyReader?: boolean;
      isDraft?: boolean;
      isAutoGenerated?: boolean;
      status?: string;
    };
  }>;
}
